In [141]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [142]:
dataset = pd.read_csv("housing.csv")

In [143]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  int64  
 3   total_rooms         20640 non-null  int64  
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  int64  
 6   households          20640 non-null  int64  
 7   median_income       20640 non-null  float64
 8   ocean_proximity     20640 non-null  object 
 9   median_house_value  20640 non-null  int64  
dtypes: float64(4), int64(5), object(1)
memory usage: 1.6+ MB


In [144]:
dataset

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                  41          880           129.0   
1        -122.22     37.86                  21         7099          1106.0   
2        -122.24     37.85                  52         1467           190.0   
3        -122.25     37.85                  52         1274           235.0   
4        -122.25     37.85                  52         1627           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                  25         1665           374.0   
20636    -121.21     39.49                  18          697           150.0   
20637    -121.22     39.43                  17         2254           485.0   
20638    -121.32     39.43                  18         1860           409.0   
20639    -121.24     39.37                  16         2785           616.0   

       population  households  median_income ocean_proximity  \
0             322         126         8.3252        NEAR BAY   
1            2401        1138         8.3014        NEAR BAY   
2             496         177         7.2574        NEAR BAY   
3             558         219         5.6431        NEAR BAY   
4             565         259         3.8462        NEAR BAY   
...           ...         ...            ...             ...   
20635         845         330         1.5603          INLAND   
20636         356         114         2.5568          INLAND   
20637        1007         433         1.7000          INLAND   
20638         741         349         1.8672          INLAND   
20639        1387         530         2.3886          INLAND   

       median_house_value  
0                  452600  
1                  358500  
2                  352100  
3                  341300  
4                  342200  
...                   ...  
20635               78100  
20636               77100  
20637               92300  
20638               84700  
20639               89400  

[20640 rows x 10 columns]

In [145]:
dataset.shape

(20640, 10)

In [146]:
df = pd.DataFrame(dataset)

In [147]:
df.shape

(20640, 10)

In [148]:
df.isna()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0          False     False               False        False           False   
1          False     False               False        False           False   
2          False     False               False        False           False   
3          False     False               False        False           False   
4          False     False               False        False           False   
...          ...       ...                 ...          ...             ...   
20635      False     False               False        False           False   
20636      False     False               False        False           False   
20637      False     False               False        False           False   
20638      False     False               False        False           False   
20639      False     False               False        False           False   

       population  households  median_income  ocean_proximity  \
0           False       False          False            False   
1           False       False          False            False   
2           False       False          False            False   
3           False       False          False            False   
4           False       False          False            False   
...           ...         ...            ...              ...   
20635       False       False          False            False   
20636       False       False          False            False   
20637       False       False          False            False   
20638       False       False          False            False   
20639       False       False          False            False   

       median_house_value  
0                   False  
1                   False  
2                   False  
3                   False  
4                   False  
...                   ...  
20635               False  
20636               False  
20637               False  
20638               False  
20639               False  

[20640 rows x 10 columns]

In [149]:
dataset.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                  41          880           129.0   
1    -122.22     37.86                  21         7099          1106.0   
2    -122.24     37.85                  52         1467           190.0   
3    -122.25     37.85                  52         1274           235.0   
4    -122.25     37.85                  52         1627           280.0   

   population  households  median_income ocean_proximity  median_house_value  
0         322         126         8.3252        NEAR BAY              452600  
1        2401        1138         8.3014        NEAR BAY              358500  
2         496         177         7.2574        NEAR BAY              352100  
3         558         219         5.6431        NEAR BAY              341300  
4         565         259         3.8462        NEAR BAY              342200

In [123]:
# dataset.drop('ocean_proximity', axis=1, inplace=True) this code drops an unnecessary column

In [150]:
dataset.tail()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
20635    -121.09     39.48                  25         1665           374.0   
20636    -121.21     39.49                  18          697           150.0   
20637    -121.22     39.43                  17         2254           485.0   
20638    -121.32     39.43                  18         1860           409.0   
20639    -121.24     39.37                  16         2785           616.0   

       population  households  median_income ocean_proximity  \
20635         845         330         1.5603          INLAND   
20636         356         114         2.5568          INLAND   
20637        1007         433         1.7000          INLAND   
20638         741         349         1.8672          INLAND   
20639        1387         530         2.3886          INLAND   

       median_house_value  
20635               78100  
20636               77100  
20637               92300  
20638               84700  
20639               89400

In [151]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  int64  
 3   total_rooms         20640 non-null  int64  
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  int64  
 6   households          20640 non-null  int64  
 7   median_income       20640 non-null  float64
 8   ocean_proximity     20640 non-null  object 
 9   median_house_value  20640 non-null  int64  
dtypes: float64(4), int64(5), object(1)
memory usage: 1.6+ MB


In [152]:
print(dataset.isnull().sum())

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
ocean_proximity         0
median_house_value      0
dtype: int64


In [153]:
dataset = dataset.dropna(axis=0)
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 20433 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20433 non-null  float64
 1   latitude            20433 non-null  float64
 2   housing_median_age  20433 non-null  int64  
 3   total_rooms         20433 non-null  int64  
 4   total_bedrooms      20433 non-null  float64
 5   population          20433 non-null  int64  
 6   households          20433 non-null  int64  
 7   median_income       20433 non-null  float64
 8   ocean_proximity     20433 non-null  object 
 9   median_house_value  20433 non-null  int64  
dtypes: float64(4), int64(5), object(1)
memory usage: 1.7+ MB


In [154]:
print(dataset.isnull().sum())

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
ocean_proximity       0
median_house_value    0
dtype: int64


In [155]:
X = dataset.iloc[:, :9]# get a copy of dataset, exclude the last column
y = dataset.iloc[:, 9].values # get an array of values from column 9

In [156]:
X

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                  41          880           129.0   
1        -122.22     37.86                  21         7099          1106.0   
2        -122.24     37.85                  52         1467           190.0   
3        -122.25     37.85                  52         1274           235.0   
4        -122.25     37.85                  52         1627           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                  25         1665           374.0   
20636    -121.21     39.49                  18          697           150.0   
20637    -121.22     39.43                  17         2254           485.0   
20638    -121.32     39.43                  18         1860           409.0   
20639    -121.24     39.37                  16         2785           616.0   

       population  households  median_income ocean_proximity  
0             322         126         8.3252        NEAR BAY  
1            2401        1138         8.3014        NEAR BAY  
2             496         177         7.2574        NEAR BAY  
3             558         219         5.6431        NEAR BAY  
4             565         259         3.8462        NEAR BAY  
...           ...         ...            ...             ...  
20635         845         330         1.5603          INLAND  
20636         356         114         2.5568          INLAND  
20637        1007         433         1.7000          INLAND  
20638         741         349         1.8672          INLAND  
20639        1387         530         2.3886          INLAND  

[20433 rows x 9 columns]

In [131]:
y = pd.Data

array([452600, 358500, 352100, ...,  92300,  84700,  89400], dtype=int64)

In [132]:
# Handling Categorical Variables (ocean_proximity)
from sklearn.preprocessing import LabelEncoder, OneHotEncoder 
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([("ocean_proximity", OneHotEncoder(), [8])], remainder="passthrough")
X = ct.fit_transform(X)

# labelencoder_x= LabelEncoder()  
# X.iloc[:, 8]= labelencoder_x.fit_transform(X.iloc[:,8])  
# onehotencoder= OneHotEncoder(categorical_features= [8])    
# X= onehotencoder.fit_transform(X).toarray() 

In [133]:
X = pd.DataFrame(X)
X

0    1    2    3    4       5      6     7       8       9       10  \
0      0.0  0.0  0.0  1.0  0.0 -122.23  37.88  41.0   880.0   129.0   322.0   
1      0.0  0.0  0.0  1.0  0.0 -122.22  37.86  21.0  7099.0  1106.0  2401.0   
2      0.0  0.0  0.0  1.0  0.0 -122.24  37.85  52.0  1467.0   190.0   496.0   
3      0.0  0.0  0.0  1.0  0.0 -122.25  37.85  52.0  1274.0   235.0   558.0   
4      0.0  0.0  0.0  1.0  0.0 -122.25  37.85  52.0  1627.0   280.0   565.0   
...    ...  ...  ...  ...  ...     ...    ...   ...     ...     ...     ...   
20428  0.0  1.0  0.0  0.0  0.0 -121.09  39.48  25.0  1665.0   374.0   845.0   
20429  0.0  1.0  0.0  0.0  0.0 -121.21  39.49  18.0   697.0   150.0   356.0   
20430  0.0  1.0  0.0  0.0  0.0 -121.22  39.43  17.0  2254.0   485.0  1007.0   
20431  0.0  1.0  0.0  0.0  0.0 -121.32  39.43  18.0  1860.0   409.0   741.0   
20432  0.0  1.0  0.0  0.0  0.0 -121.24  39.37  16.0  2785.0   616.0  1387.0   

           11      12  
0       126.0  8.3252  
1      1138.0  8.3014  
2       177.0  7.2574  
3       219.0  5.6431  
4       259.0  3.8462  
...       ...     ...  
20428   330.0  1.5603  
20429   114.0  2.5568  
20430   433.0  1.7000  
20431   349.0  1.8672  
20432   530.0  2.3886  

[20433 rows x 13 columns]

## Splitting the data into training and testing set

In [134]:
from sklearn.model_selection import train_test_split

In [135]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

## Fitting multiple linear regression in our model

In [136]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [137]:
# from sklearn import metrics
pred = regressor.predict(X_test)

In [138]:
pred

array([189847.43191477, 175807.01704458, 123403.18401073, ...,
       155109.64616819, 217118.61734572, 250189.80917342])

In [139]:
print('Train score: ', regressor.score(X_train, y_train))
print('Test score: ', regressor.score(X_test, y_test))

Train score:  0.6447528579536206
Test score:  0.6526096664530914


## Making Predictions and outputing the predicted results using a given set of values

In [140]:
prediction = regressor.predict([[0.0, 0.0, 0.0, 1.0, 0.0, -122.23, 37.88, 41.0, 880.0, 129.0, 322.0, 126.0, 8.3252]])
prediction

array([410397.63257046])